### ISSUE TITLE
Tool crashes on run

### ISSUE THREAD

**Issue by oliverkane** [sciapp/gitlab-registry-cleanup#2]
Hi there. I'd like to report that I'm getting the below output for any combination (or also none)  flags/args.

```shell
sevenless@eightmore:~$ gitlab-registry-cleanup 
Traceback (most recent call last):
  File "/home/sevenless/.local/bin/gitlab-registry-cleanup", line 7, in <module>
    from gitlab_registry_cleanup.cli import main
  File "/home/sevenless/.local/lib/python2.7/site-packages/gitlab_registry_cleanup/cli.py", line 15
SyntaxError: Non-ASCII character '\xc2' in file /home/sevenless/.local/lib/python2.7/site-packages/gitlab_registry_cleanup/cli.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
I'm running a virgin ubuntu 18.04 install on a physical AMD based machine. I'm not sure what else I can provide, so I'll happily do digging if you let me know where to look. Going to investigate the files it mentioned for now.

**Comment by IngoMeyer441** [comment]
Hey, thanks for your bug report. This project is Python 3.3+ only. You can request a installation for Python 3 by selecting Python 3 pip explicitly:
```bash
python3 -m pip install gitlab-registry-cleanup
```
However, this package should not be installable on Python 2 at all to avoid your issue. I will add
```
python_requires='>=3.3'
```
to the `setup.py` script.

**Comment by IngoMeyer441** [comment]
Should be fixed with [v0.1.1](https://pypi.org/project/gitlab-registry-cleanup/0.1.1/). But please feel free to reopen the issue if you still experience problems.

**Comment by oliverkane** [comment]
Many thanks good sir!  I'm not familiar with using the python3 version of pip. Will that run side-by-side with my other v2 tools or will that be a system wide change?

**Comment by IngoMeyer441** [comment]
Different Python (minor) versions are isolated from each other because packages for different versions are installed in different locations. On Debian / Ubuntu packages installed with pip go to
```
/usr/local/lib/pythonX.X/dist-packages/
``` 
However, on Linux startup scripts like `gitlab-registry-cleanup` are installed to `/usr/local/bin` regardless of their Python version; if you install a tool for different Python versions, startup scripts are overwritten by the latest install.
