### ISSUE TITLE
Could not delete image

### ISSUE THREAD

**Issue by ivugrinec** [sciapp/gitlab-registry-cleanup#5]
Hi, 
I am an end user, trying to use gitlab-registry-cleanup script. Script runs ok in "dry-run" but then it fails with 
"Could not delete image sha256:b664d8b24d66bee8336bd5bd9c203617e1b1474ddbbb764d401f55ff2a95cd7c in repository tdce/test-rig."  This error occurs for every image listed. 

I am using latest GitLAB on latest openSuse LEAP 15 (based on SLES 15).  I am using root user to execute script and root (admin) user as registry authorization. 

 Any idea why would this happen?

**Comment by IngoMeyer441** [comment]
Hey,
do you use the GitLab admin password or an authorization token for root access?

**Comment by ivugrinec** [comment]
Admin password.

**Comment by ivugrinec** [comment]
![image](https://user-images.githubusercontent.com/38259498/42082239-c3c08e0a-7b87-11e8-9bd5-4a3518462939.png)

**Comment by IngoMeyer441** [comment]
Hmm, is it correct that your GitLab url ends with `.local`?
Can you try to fetch the registry catalog by hand? That can be done with `curl` from any machine that has web access to your GitLab server:
1. Fetch an access token for the registry catalog:
    ```bash
    curl --user root 'https://gitlab.mobilisis.local/jwt/auth? 
    client_id=docker&service=container_registry&scope=registry:catalog:*'
    ```
2. Use the token to fetch the catalog:
    ```bash
    curl -H 'Authorization: Bearer eyXXXXXXX.....' https://registry.mobilisis.com/v2/_catalog
    ```

**Comment by ivugrinec** [comment]
This is what tried and failed: 
![image](https://user-images.githubusercontent.com/38259498/42102025-1665e2e4-7bc5-11e8-8cdd-fff1317a1d48.png)

**Comment by ivugrinec** [comment]
Some more diagnostic info: 
![image](https://user-images.githubusercontent.com/38259498/42102131-562b7cea-7bc5-11e8-9d96-9b5b5755f9df.png)

**Comment by IngoMeyer441** [comment]
Ok, it is an SSL problem. SSL verification fails for the query to the GitLab server and that is probably the reason why the Python code fails as well.

**Comment by IngoMeyer441** [comment]
Do you usually use GitLab with plain `http` or do you use internal TLS/SSL certificates?

**Comment by ivugrinec** [comment]
Yes. We first started using gitlab on http and then published registry on https  *.com domain because we had the public SSL certificate for it. 

![image](https://user-images.githubusercontent.com/38259498/42103128-766d4120-7bc8-11e8-8c42-8042a0639880.png)

**Comment by IngoMeyer441** [comment]
Ok, then
```bash
curl --user root 'http://gitlab.mobilisis.local/jwt/auth? 
client_id=docker&service=container_registry&scope=registry:catalog:*'
```
should work instead. Sending an admin password over http is very insecure but if you call `curl` from the GitLab server itself the http connection should be handled without real network access.

Currently, this project cannot handle GitLab instances over plain http but I could add an option for it.

**Comment by ivugrinec** [comment]
Ok, now i can fetch catalog using the token i get form curl. 

So if understand correctly the problem is that you need to access both services: 
- gitlab (on my setup listen at TCP/80-http)
- registry (on my setup at TCP/443-https)
The problem is that i am not using standard port 5000 for registry - but 443 wich then cannot be used for GitLab..  Any workaround?

**Comment by IngoMeyer441** [comment]
The tool only needs access to TCP/443 https for both GitLab and registry (the registry port 5000 is not used at all). In the current version, it is not possible at all to use http because the program [always adds `https://` automatically](https://github.com/sciapp/gitlab-registry-cleanup/blob/develop/gitlab_registry_cleanup/cli.py#L159). I could only add an option to use plain http instead. 

How about this:
```bash
gitlab-registry-cleanup --allow-plain-http -g http://gitlab.mobilisis.local -r https://registry.mobilisis.com
```
By specifying `http://` and `https://` explicitly, it would be possible to use GitLab with plain http and your registry with https.

**Comment by ivugrinec** [comment]
It would be really great if you could release a version that could do that. 
Thanks. Please find the time. Any plans? 

On one of the next revisions it would also be very useful if i could add the repository path from which untagged images will be deleted. For example only delete untagged images from one ore two largest and most commonly used images. I could then also create some test repos and try the script in small scale, minimizing risk of deleting images that i didn't want to delete. Just a suggestion.. The http fix is important...

**Comment by IngoMeyer441** [comment]
I think I can spend some time on this issue tomorrow or on Sunday. Should not be much work.

**Comment by ivugrinec** [comment]
That's great. 

Can i just ask you: What would be the correct configuration of Gitlab and Gitlab Docker Registry that  gitlab-registry-cleanup tool expect? Maybe i could reconfigure it.. (so you won't need to work on the new release).

**Comment by IngoMeyer441** [comment]
You would need a domain + an SSL certificate for your GitLab server. Then you can [configure GitLab with an external URL that starts with `https://`](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab) and [add the certificate](https://docs.gitlab.com/omnibus/settings/nginx.html#change-the-default-port-and-the-ssl-certificate-locations). After that, this tool should work as expected.

**Comment by ivugrinec** [comment]
OK, done that. Now it looks like it marks images for deletion. Thank you. Now i just need to wait and run GC.  Thank you for help and advice's.

**Comment by IngoMeyer441** [comment]
:+1: Great

**Comment by ivugrinec** [comment]
System reconfigured to match expected state need for tool to work.
