### ISSUE TITLE
add support specifying CREDENTIALS via env/commandline

### ISSUE THREAD

**Issue by glensc** [sciapp/gitlab-registry-cleanup#7]
```
  -c CREDENTIALS_FILE, --credentials-file CREDENTIALS_FILE
                        path to a file containing username and password/access
                        token (on two separate lines)
```

i'm running this tool in docker (docker-compose) and it's more convenient (in my usecase) to specify secrets via `.env` than create multiple configuration files.

so could it be possible to specify these credentials without extra file? i.e via commandline options or environment variables.

**Comment by IngoMeyer441** [comment]
Hey,
starting with f5f999df8fb0f2010a24b677650d4f5d74fde4fb passwords can be read from stdin with input redirection, so you could use
```bash
echo "${PASSWORD} | gitlab-registry-cleanup -u "${USER} ...
```
in your scripts. Would this be ok?

**Comment by glensc** [comment]
it might. but please tag a release for testing the change.

**Comment by IngoMeyer441** [comment]
Ok, [v0.1.5 is installable from PyPI](https://pypi.org/project/gitlab-registry-cleanup/0.1.5/).

**Comment by glensc** [comment]
thanks. this seems to work.
