### ISSUE TITLE
crashes on centos 7 and python 3.4

### ISSUE THREAD

**Issue by janisblaus** [sciapp/gitlab-registry-cleanup#8]
```
[root@dock srv]# gitlab-registry-cleanup
Traceback (most recent call last):
  File "/usr/bin/gitlab-registry-cleanup", line 7, in <module>
    from gitlab_registry_cleanup.cli import main
  File "/usr/lib/python3.4/site-packages/gitlab_registry_cleanup/cli.py", line 9, in <module>
    from typing import cast, Any, Callable
ImportError: No module named 'typing'

```

**Comment by janisblaus** [comment]
When tried to install on gitlab docker container, received this one

```
    Complete output from command python setup.py egg_info:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tzdywb92/pycparser/

```

**Comment by IngoMeyer441** [comment]
Thanks for your bug report! :+1:
The missing `typing` module was introduced in Python 3.5 which is the reason for the error you get on CentOS 7. However, `typing` has been backported for older Python versions. I will add it to the package requirements.

**Comment by IngoMeyer441** [comment]
Should be fixed with commit ef229c8278dc3628c6cdf8931d0b198772111eaa. The new version v0.1.3 is already available [on PyPI](https://pypi.org/project/gitlab-registry-cleanup/0.1.3/).

**Comment by janisblaus** [comment]
Cool will test that. Will it fix the same for docker omnibus?

**Comment by IngoMeyer441** [comment]
I am not quite sure why you get this error message on Docker Omnibus. Did you install the package with `pip install gitlab-registry-cleanup`?

**Comment by nopnop** [comment]
@janisblaus Facing the same problem with Docker Omnibus, I found another solution which may suit you:

I start another container with up-to-date python release, and I mount my gitlab data volume
```
docker run -it --rm -v gitlab-data:/var/opt/gitlab python:3 bash
``` 
(where `gitlab-data` is the docker volume used in the omnibus release, see too `--volume-from <container>` if you do not use docker volume) 

Now, you can simply execute `pip install gitlab-registry-cleanup` and use it without friction. Thereby only `gitlab-ctl registry-garbage-collect` needs to be executed in the omnibus container.  

(Thanks a lot @IngoHeimbach, this tool is fantastic!)

**Comment by janisblaus** [comment]
ah @nopnop it worked like a charm, thank you! Great workaround!

**Comment by IngoMeyer441** [comment]
If you install some additional packages, it is possible to install `gitlab-registry-cleanup` in the GitLab container itself:
```bash
apt update && \
apt install -y --no-install-recommends build-essential libssl-dev libffi-dev python3-dev python3-pip python3-setuptools python3-wheel && \
rm -rf /var/lib/apt/lists/* && \
/usr/bin/pip3 install gitlab-registry-cleanup
```
But this way, your container will use quite a lot of additional disk space so @nopnop's suggestion seems more elegant.
